[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "npx-mcp-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.15"
dependencies = [
    "oxygent==1.0.9",
]

[project.scripts]
npx-mcp-template = "main:entry_point"

[tool.hatch.build.targets.wheel]
only-include = ["main.py"]
